services:
  database:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=chatvault'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=usr_chatvault'
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    ports:
      - 8081:8080
  chatvault:
    build: ./
    environment:
      - DATABASE_URL=postgres://usr_chatvault:secret@database:5432/chatvault
      - CHATVAULT_BUCKET_PROVIDER=filesystem
      - CHATVAULT_BUCKET_ROOT=/opt/chatvault/archive
      - CHATVAULT_IMPORT_DIR=/opt/chatvault/import
      - CHATVAULT_SCRATCH_DIR=/opt/chatvault/scratch
      - CHATVAULT_MSGPARSER_DATEFORMAT=dd/MM/yyyy HH:mm
    ports:
      - 8080:8080
    volumes:
      - '/opt/chatvault:/opt/chatvault'
    depends_on:
      - database
